[package]
name = "nanooctopus"
version = "0.3.0"
edition = "2024"
description = "🐙 A lightweight, `no_std` HTTP server for embedded systems built on top of Embassy networking."
documentation = "https://docs.rs/nanooctopus"
repository = "https://github.com/kdimonych/nanooctopus"
license = "MIT"
keywords = ["no_std", "embedded", "async", "http_server", "websockets"]
authors = ["kdimonych <k.dimonych@gmail.com>"]

[features]
default = []
std = ["nanooctopus_server/std"]
defmt = ["nanooctopus_server/defmt"]
log = ["nanooctopus_server/log"]
# The `bench_masker` feature is used to enable dependencies and features required for benchmarking,
# such as Criterion and the optimized masking implementation.
bench_masker = ["nanooctopus_server/bench_masker"]

[dependencies]
nanooctopus_server = { workspace = true }

[dev-dependencies]
#byte-unit = "5"
futures-lite = "2.0"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4"
mockall = "0.14"
predicates-core = "1.0"
env_logger = "0.11"
static_assertions = "1.1"
edge-nal = { workspace = true }
log = { workspace = true }
embassy-time = { version = "0.5", features = ["std", "generic-queue-64"] }
edge-nal-std = { version = "0.7", default-features = false }

[[example]]
name = "hello_world"
required-features = ["std", "log"]

[workspace]
members = [".", "nanooctopus_server"]
exclude = ["demos/rasberry_pico_w"]

[workspace.dependencies]
defmt = { version = "1", default-features = false, features = ["ip_in_core"] }
log = { version = "0.4", default-features = false }
defmt-or-log = { version = "0.2.3", default-features = false }
edge-nal = { version = "0.7", default-features = false }
edge-http = { version = "0.8", default-features = false, features = ["io"] }
edge-ws = { version = "0.8", default-features = false, features = ["io"] }
heapless = { version = "0.9", default-features = false }
embedded-io-async = { version = "0.7", default-features = false }
byte-unit = { version = "5.2", default-features = false, features = ["byte"] }

nanooctopus_server = { version = "0.3.0", path = "nanooctopus_server", default-features = false }
