[alias]
build_embedded = "build --target thumbv6m-none-eabi --features defmt"
build_host = "build --features std --features log"
check_embedded = "check --target thumbv6m-none-eabi  --features defmt"
run_embedded = "run --target thumbv6m-none-eabi --features defmt"
check_host = "check --features std --features log"
build_hello_world_example = "build --package nanooctopus --example hello_world --features std --features log"
run_hello_world_example = "run --package nanooctopus --example hello_world --features std --features log"

[env]
DEFMT_LOG = "debug"
DBG_PRINT = "1"
