[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip YOUR_CHIP"
rustflags = ["-C", "link-arg=-Tlink.x"]


[alias]
build-embedded = "build --target thumbv6m-none-eabi"
build-host = "build --features std"
check-embedded = "check --target thumbv6m-none-eabi"
run-embedded = "run --target thumbv6m-none-eabi"
check-host = "check --features std"
run-host-example = "run --example hello_world --features std"

[env]
DEFMT_LOG = "debug"
DBG_PRINT = "1"
